DbSettings:
  MigrationConnectionString: postgres://user:mypassword@order-pgbouncer:6432/postgres?sslmode=disable
  ConnectionString: postgres://user:mypassword@order-pgbouncer:6432/postgres?sslmode=disable

OmsPublisherSettings:
  RabbitMqSettings:
    Host: order-rabbitmq
    Port: 5672
    User: user
    Password: mypassword
  Exchange: oms
  ExchangeMappings:
    - Queue: oms.order.created
      RoutingKeyPattern: order.created
      DeadLetterSettings:
        Dlx: oms.order.dlx
        RoutingKey: order.created
    - Queue: oms.order.status.changed
      RoutingKeyPattern: order.status.changed
      DeadLetterSettings:
        Dlx: oms.order.dlx
        RoutingKey: order.status.changed
    - Queue: public.oms.order.created
      RoutingKeyPattern: order.created
    - Queue: public.oms.order.status.changed
      RoutingKeyPattern: order.status.changed
    - Queue: oms.logs
      RoutingKeyPattern: order.*

HttpServerSettings:
  Port: 5000

GrpcServerSettings:
  Port: 50051
