DbSettings:
  MigrationConnectionString: postgres://user:mypassword@order-pgbouncer:6432/postgres?sslmode=disable
  ConnectionString: postgres://user:mypassword@order-pgbouncer:6432/postgres?sslmode=disable

OmsProducerSettings:
  KafkaSettings:
    BootstrapServers: order-kafka:29092
    ClientId: universe-labs-oms
  OrderCreatedTopic: oms_order_created
  OrderStatusChangedTopic: oms_order_status_changed

HttpServerSettings:
  Port: 5000

GrpcServerSettings:
  Port: 50051
